### ISSUE TITLE
你好，我是你嫖到项目的作者，我就想问一下，哪个git热门上有我的项目？

### ISSUE THREAD

**Issue by wangyupo** [TiankeTt/vueDefault#2]
附原项目地址：https://github.com/wangyupo/vue-vuex-router

**Comment by TiankeTt** [comment]
好像是掘金还是啥的，有个推荐的放的你的git地址。如有冒犯，这边我就设置关掉。不好意思。我这个仅供自己使用。

**Comment by TiankeTt** [comment]
> 附原项目地址：[https](https://github.com/wangyupo/vue-vuex-router) : [//github.com/wangyupo/vue-vuex-router](https://github.com/wangyupo/vue-vuex-router)

好像是掘金还是啥的，有个推荐的放的你的git地址。如有冒犯，这边我就设置关掉。不好意思。我这个仅供自己使用。

**Comment by TiankeTt** [comment]
> 附原项目地址：[https](https://github.com/wangyupo/vue-vuex-router) : [//github.com/wangyupo/vue-vuex-router](https://github.com/wangyupo/vue-vuex-router)

![image](https://user-images.githubusercontent.com/27058669/72230218-f6f59680-35ee-11ea-8773-b6b735c2549b.png)
具体是一个掘金帖子下的评论

**Comment by wangyupo** [comment]
> > 附原项目地址：[https](https://github.com/wangyupo/vue-vuex-router) : [//github.com/wangyupo/vue-vuex-router](https://github.com/wangyupo/vue-vuex-router)
> 
> 好像是掘金还是啥的，有个推荐的放的你的git地址。如有冒犯，这边我就设置关掉。不好意思。我这个仅供自己使用。

哦，这个啊，没事的，你用吧。

**Comment by TiankeTt** [comment]
> > > 附原项目地址：[https](https://github.com/wangyupo/vue-vuex-router) : [//github.com/wangyupo/vue-vuex-router](https://github.com/wangyupo/vue-vuex-router)
> > 
> > 
> > 好像是掘金还是啥的，有个推荐的放的你的git地址。如有冒犯，这边我就设置关掉。不好意思。我这个仅供自己使用。
> 
> 哦，这个啊，没事的，你用吧。

感谢。看了您写的东西。学到了挺多。优秀
